// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nodus.Database.Migrator.Contexts;

#nullable disable

namespace Nodus.Database.Migrator.Migrations.Admin
{
    [DbContext(typeof(AdminContext))]
    [Migration("20230525112808_ChangeTripRoleSystem")]
    partial class ChangeTripRoleSystem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Nodus.Database.Models.Admin.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Feature for super admin only",
                            Name = "ManageCompanies"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allows to read users personal information",
                            Name = "ReadUsers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allows to update users personal information",
                            Name = "WriteUsers"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Allows to access trips",
                            Name = "ReadTrips"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Allows to manage trips",
                            Name = "WriteTrips"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Allows to access bills",
                            Name = "ReadBills"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Allows to create bills",
                            Name = "WriteBills"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Additional feature",
                            Name = "AccessStatistics"
                        });
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEpxired")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Super admin role for admin-side workers",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.RoleFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnName("FeatureID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("FeatureId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleFeatures");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            RoleId = -1
                        });
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("acb93144-58b2-48e2-a4e8-e6a6fb138f06"),
                            Created = new DateTime(2023, 5, 25, 13, 28, 7, 945, DateTimeKind.Local).AddTicks(404),
                            Email = "nodus.admin@email.com",
                            IsActive = true,
                            PasswordHash = new byte[] { 191, 62, 228, 119, 85, 50, 10, 68, 224, 66, 237, 157, 108, 153, 19, 10, 120, 232, 154, 217, 48, 109, 118, 176, 179, 23, 34, 5, 20, 125, 36, 190 },
                            PasswordSalt = new byte[] { 58, 138, 81, 250, 144, 47, 111, 56, 113, 130, 18, 245, 7, 223, 241, 254, 160, 137, 187, 235, 233, 233, 198, 47, 169, 98, 155, 144, 222, 150, 22, 111 },
                            PhoneNumber = "1234567890",
                            RoleId = -1
                        });
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Link", b =>
                {
                    b.HasOne("Nodus.Database.Models.Admin.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Role", b =>
                {
                    b.HasOne("Nodus.Database.Models.Admin.Company", "Company")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.RoleFeature", b =>
                {
                    b.HasOne("Nodus.Database.Models.Admin.Feature", "Feature")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nodus.Database.Models.Admin.Role", "Role")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.User", b =>
                {
                    b.HasOne("Nodus.Database.Models.Admin.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Company", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Feature", b =>
                {
                    b.Navigation("RoleFeatures");
                });

            modelBuilder.Entity("Nodus.Database.Models.Admin.Role", b =>
                {
                    b.Navigation("RoleFeatures");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
