#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Nodus.Jamal.Service/Nodus.Jamal.Service.csproj", "Nodus.Jamal.Service/"]
RUN dotnet restore "Nodus.Jamal.Service/Nodus.Jamal.Service.csproj"
COPY . .
WORKDIR "/src/Nodus.Jamal.Service"
RUN dotnet build "Nodus.Jamal.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Nodus.Jamal.Service.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Nodus.Jamal.Service.dll"]